repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.json
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args:
          - "--style"
          - "{based_on_style: google, column_limit: 120, indent_width: 2, continuation_indent_width: 2}"
